services:
  # 1. La Base de Données
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=LOCAL_GHOST
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tomfeu83
    

  # 2. Le Backend (Django Ninja)
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:tomfeu83@db:5432/LOCAL_GHOST
      - DEBUG=1
    depends_on:
      - db
  # 3. Le Frontend (React)
  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # Utile pour le hot-reload sur certains OS
    stdin_open: true
    depends_on:
      - backend

volumes:
  postgres_data: