# Generated by Django 5.2.10 on 2026-02-01 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liste_amis',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='status_discussion',
            field=models.CharField(choices=[('hote', 'hote'), ('invité', 'invite')], default='hote'),
        ),
        migrations.AddField(
            model_name='user',
            name='statut',
            field=models.CharField(choices=[('En ligne', 'en ligne'), ('Hors ligne', 'hors ligne')], default='hors ligne'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
