# Generated by Django 5.2.11 on 2026-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_liste_amis_user_status_discussion_user_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='statut',
            field=models.CharField(choices=[('en_ligne', 'en ligne'), ('hors_ligne', 'hors ligne')], default='hors_ligne'),
        ),
    ]
